from pathlib import Path

from docx import Document
from docx.shared import Pt


def build_document() -> Document:
    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Arial"
    style.font.size = Pt(10)

    columns = [
        "Attribute",
        "Datatype",
        "Constraint",
        "Nullable",
        "Default",
        "Description",
    ]

    def add_entity(name: str, desc: str, rows: list[dict]):
        doc.add_heading(name, level=2)
        if desc:
            doc.add_paragraph(desc)
        table = doc.add_table(rows=len(rows) + 1, cols=len(columns))
        table.style = "Table Grid"
        for idx, col in enumerate(columns):
            table.cell(0, idx).text = col
        for r_idx, row in enumerate(rows, start=1):
            for c_idx, col in enumerate(columns):
                table.cell(r_idx, c_idx).text = str(row.get(col, ""))
        doc.add_paragraph("")

    add_entity(
        "BaseEntity",
        "Truong chung cho moi entity MongoDB",
        [
            {
                "Attribute": "id (_id)",
                "Datatype": "ObjectId",
                "Constraint": "PK",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Khoa chinh, alias _id",
            },
            {
                "Attribute": "created_at",
                "Datatype": "datetime",
                "Constraint": "auto-set",
                "Nullable": "No",
                "Default": "now() UTC",
                "Description": "Thoi diem tao ban ghi",
            },
            {
                "Attribute": "updated_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Cap nhat cuoi",
            },
        ],
    )

    add_entity(
        "DatasetProject",
        "Metadata dataset luu trong MongoDB",
        [
            {
                "Attribute": "user_id",
                "Datatype": "ObjectId",
                "Constraint": "FK users._id",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Chu so huu",
            },
            {
                "Attribute": "name",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Ten dataset",
            },
            {
                "Attribute": "description",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Mo ta",
            },
            {
                "Attribute": "file_name",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Ten file upload",
            },
            {
                "Attribute": "file_path",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Duong dan luu tru",
            },
            {
                "Attribute": "source",
                "Datatype": "str",
                "Constraint": "enum: upload,...",
                "Nullable": "No",
                "Default": "upload",
                "Description": "Nguon nhap lieu",
            },
            {
                "Attribute": "rows",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "So dong",
            },
            {
                "Attribute": "size_bytes",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Kich thuoc file",
            },
            {
                "Attribute": "columns",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Danh sach cot",
            },
            {
                "Attribute": "mapped_fields",
                "Datatype": "DatasetMapping",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "{}",
                "Description": "Mapping build_id/repo_name",
            },
            {
                "Attribute": "stats",
                "Datatype": "DatasetStats",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "{}",
                "Description": "Coverage/missing/duplicate/build_coverage",
            },
            {
                "Attribute": "source_languages",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Ngon ngu nguon",
            },
            {
                "Attribute": "test_frameworks",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Framework test phat hien",
            },
            {
                "Attribute": "preview",
                "Datatype": "List[Dict]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Sample du lieu",
            },
            {
                "Attribute": "validation_status",
                "Datatype": "str",
                "Constraint": "enum pending|validating|completed|failed|cancelled",
                "Nullable": "No",
                "Default": "pending",
                "Description": "Trang thai validate",
            },
            {
                "Attribute": "validation_task_id",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Celery task",
            },
            {
                "Attribute": "validation_started_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Bat dau validate",
            },
            {
                "Attribute": "validation_completed_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Hoan tat validate",
            },
            {
                "Attribute": "validation_progress",
                "Datatype": "int",
                "Constraint": "0-100",
                "Nullable": "No",
                "Default": "0",
                "Description": "Tien do",
            },
            {
                "Attribute": "validation_stats",
                "Datatype": "ValidationStats",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "{}",
                "Description": "Thong ke repo/build",
            },
            {
                "Attribute": "validation_error",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Thong bao loi",
            },
            {
                "Attribute": "setup_step",
                "Datatype": "int",
                "Constraint": "1-3",
                "Nullable": "No",
                "Default": "1",
                "Description": "Tien trinh cau hinh",
            },
        ],
    )

    add_entity(
        "DatasetBuild",
        "Moi dong CSV sau validate",
        [
            {
                "Attribute": "dataset_id",
                "Datatype": "ObjectId",
                "Constraint": "FK dataset_projects._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Lien ket dataset",
            },
            {
                "Attribute": "build_id_from_csv",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Build ID tu CSV",
            },
            {
                "Attribute": "repo_name_from_csv",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Repo tu CSV",
            },
            {
                "Attribute": "status",
                "Datatype": "enum DatasetBuildStatus",
                "Constraint": "pending|found|not_found|error",
                "Nullable": "No",
                "Default": "pending",
                "Description": "Ket qua tra cuu",
            },
            {
                "Attribute": "validation_error",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Loi validate",
            },
            {
                "Attribute": "validated_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Thoi diem validate",
            },
            {
                "Attribute": "repo_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_repositories._id",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Repo noi bo",
            },
            {
                "Attribute": "workflow_run_id",
                "Datatype": "ObjectId",
                "Constraint": "FK workflow_runs._id",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Workflow run tim thay",
            },
        ],
    )

    add_entity(
        "EnrichmentRepository",
        "Repo duoc auto-import/validate phuc vu enrichment",
        [
            {
                "Attribute": "dataset_id",
                "Datatype": "ObjectId",
                "Constraint": "FK dataset_projects._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Dataset lien quan",
            },
            {
                "Attribute": "full_name",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "owner/repo",
            },
            {
                "Attribute": "ci_provider",
                "Datatype": "enum CIProvider",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "github_actions",
                "Description": "Nguon CI",
            },
            {
                "Attribute": "validation_status",
                "Datatype": "enum RepoValidationStatus",
                "Constraint": "pending|valid|invalid|not_found|error",
                "Nullable": "No",
                "Default": "pending",
                "Description": "Ket qua kiem tra repo",
            },
            {
                "Attribute": "validation_error",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Loi validate",
            },
            {
                "Attribute": "validated_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Thoi diem validate",
            },
            {
                "Attribute": "github_repo_id",
                "Datatype": "int",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Repo id GitHub",
            },
            {
                "Attribute": "default_branch",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Nganh mac dinh",
            },
            {
                "Attribute": "is_private",
                "Datatype": "bool",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "False",
                "Description": "Repo private?",
            },
            {
                "Attribute": "builds_total",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Tong builds",
            },
            {
                "Attribute": "builds_found",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Build tim thay",
            },
            {
                "Attribute": "builds_not_found",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Build khong tim thay",
            },
            {
                "Attribute": "source_languages",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Ngon ngu",
            },
            {
                "Attribute": "test_frameworks",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Framework test",
            },
        ],
    )

    add_entity(
        "EnrichmentBuild",
        "Build duoc extract dac trung (enrichment)",
        [
            {
                "Attribute": "enrichment_repo_id",
                "Datatype": "ObjectId",
                "Constraint": "FK enrichment_repositories._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Repo enrichment",
            },
            {
                "Attribute": "dataset_id",
                "Datatype": "ObjectId",
                "Constraint": "FK dataset_projects._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Dataset goc",
            },
            {
                "Attribute": "build_id",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Build id (CI)",
            },
            {
                "Attribute": "commit_sha",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "SHA commit",
            },
            {
                "Attribute": "extraction_status",
                "Datatype": "enum EnrichmentExtractionStatus",
                "Constraint": "pending|completed|partial|failed",
                "Nullable": "No",
                "Default": "pending",
                "Description": "Trang thai extract",
            },
            {
                "Attribute": "error_message",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Loi",
            },
            {
                "Attribute": "features",
                "Datatype": "Dict",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "{}",
                "Description": "Feature da extract",
            },
        ],
    )

    add_entity(
        "EnrichmentJob",
        "Job chay enrichment CSV -> dac trung",
        [
            {
                "Attribute": "dataset_id",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Dataset duoc enrich",
            },
            {
                "Attribute": "user_id",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Nguoi khoi tao",
            },
            {
                "Attribute": "status",
                "Datatype": "enum",
                "Constraint": "pending|running|completed|failed|cancelled",
                "Nullable": "No",
                "Default": "pending",
                "Description": "Trang thai job",
            },
            {
                "Attribute": "total_rows",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Tong dong",
            },
            {
                "Attribute": "processed_rows",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Da xu ly",
            },
            {
                "Attribute": "enriched_rows",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Thanh cong",
            },
            {
                "Attribute": "failed_rows",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "That bai",
            },
            {
                "Attribute": "skipped_rows",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Bo qua",
            },
            {
                "Attribute": "selected_features",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Danh sach feature duoc chon",
            },
            {
                "Attribute": "repos_auto_imported",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Repo auto import",
            },
            {
                "Attribute": "repos_failed_import",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Repo import loi",
            },
            {
                "Attribute": "started_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Bat dau",
            },
            {
                "Attribute": "completed_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Hoan tat",
            },
            {
                "Attribute": "error",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Thong bao loi tong",
            },
            {
                "Attribute": "row_errors",
                "Datatype": "List[dict]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Loi theo dong",
            },
            {
                "Attribute": "output_file",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Duong dan file enriched",
            },
            {
                "Attribute": "celery_task_id",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Tracking Celery",
            },
        ],
    )

    add_entity(
        "DatasetTemplate",
        "Template feature cho import repo",
        [
            {
                "Attribute": "name",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Ten template",
            },
            {
                "Attribute": "description",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Mo ta",
            },
            {
                "Attribute": "feature_names",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Danh sach feature",
            },
            {
                "Attribute": "tags",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Tag",
            },
            {
                "Attribute": "source",
                "Datatype": "str",
                "Constraint": "enum seed|custom",
                "Nullable": "No",
                "Default": "seed",
                "Description": "Nguon template",
            },
        ],
    )

    add_entity(
        "ExportJob",
        "Theo doi job export du lieu lon",
        [
            {
                "Attribute": "repo_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_repositories._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Repo nguon",
            },
            {
                "Attribute": "user_id",
                "Datatype": "ObjectId",
                "Constraint": "FK users._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Nguoi yeu cau",
            },
            {
                "Attribute": "format",
                "Datatype": "enum ExportFormat",
                "Constraint": "csv|json",
                "Nullable": "No",
                "Default": "csv",
                "Description": "Dinh dang",
            },
            {
                "Attribute": "status",
                "Datatype": "enum ExportStatus",
                "Constraint": "pending|processing|completed|failed",
                "Nullable": "No",
                "Default": "pending",
                "Description": "Trang thai",
            },
            {
                "Attribute": "features",
                "Datatype": "List[str]",
                "Constraint": "filter",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Chon feature",
            },
            {
                "Attribute": "start_date",
                "Datatype": "datetime",
                "Constraint": "filter",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Tu ngay",
            },
            {
                "Attribute": "end_date",
                "Datatype": "datetime",
                "Constraint": "filter",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Den ngay",
            },
            {
                "Attribute": "build_status",
                "Datatype": "str",
                "Constraint": "filter",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Trang thai build",
            },
            {
                "Attribute": "total_rows",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Tong so dong",
            },
            {
                "Attribute": "processed_rows",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Da xu ly",
            },
            {
                "Attribute": "file_path",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Duong dan ket qua",
            },
            {
                "Attribute": "file_size",
                "Datatype": "int",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Kich thuoc",
            },
            {
                "Attribute": "error_message",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Loi",
            },
            {
                "Attribute": "completed_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Hoan tat",
            },
        ],
    )

    add_entity(
        "FailedScan",
        "Theo doi scan that bai can xu ly",
        [
            {
                "Attribute": "repo_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_repositories._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Repo lien quan",
            },
            {
                "Attribute": "build_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_builds._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Build bi loi",
            },
            {
                "Attribute": "job_id",
                "Datatype": "ObjectId",
                "Constraint": "FK scan_jobs._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Scan job",
            },
            {
                "Attribute": "commit_sha",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Commit",
            },
            {
                "Attribute": "reason",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Thong bao loi",
            },
            {
                "Attribute": "error_type",
                "Datatype": "enum ScanErrorType",
                "Constraint": "scan_error|config_error",
                "Nullable": "No",
                "Default": "scan_error",
                "Description": "Loai loi",
            },
            {
                "Attribute": "status",
                "Datatype": "enum ScanStatus",
                "Constraint": "pending|queued|resolved",
                "Nullable": "No",
                "Default": "pending",
                "Description": "Tinh trang xu ly",
            },
            {
                "Attribute": "config_override",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Noi dung sonar-project override",
            },
            {
                "Attribute": "config_source",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Nguon cau hinh",
            },
            {
                "Attribute": "retry_count",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "So lan retry",
            },
            {
                "Attribute": "resolved_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Thoi diem giai quyet",
            },
        ],
    )

    add_entity(
        "GithubInstallation",
        "Luu GitHub App installation",
        [
            {
                "Attribute": "installation_id",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "ID installation",
            },
            {
                "Attribute": "account_login",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Login chu so huu",
            },
            {
                "Attribute": "account_type",
                "Datatype": "str",
                "Constraint": "User|Organization",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Loai tai khoan",
            },
            {
                "Attribute": "installed_at",
                "Datatype": "datetime",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Thoi diem cai",
            },
            {
                "Attribute": "revoked_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Thu hoi",
            },
            {
                "Attribute": "uninstalled_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Go bo",
            },
            {
                "Attribute": "suspended_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Tam dung",
            },
        ],
    )

    add_entity(
        "GithubToken",
        "Token ca nhan GitHub (hash luu DB)",
        [
            {
                "Attribute": "token_hash",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "SHA-256 token",
            },
            {
                "Attribute": "masked_token",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Hien thi cuoi 4 ky tu",
            },
            {
                "Attribute": "label",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "\"\"",
                "Description": "Nhan nguoi dung",
            },
            {
                "Attribute": "status",
                "Datatype": "str",
                "Constraint": "enum active|rate_limited|invalid|disabled",
                "Nullable": "No",
                "Default": "active",
                "Description": "Trang thai",
            },
            {
                "Attribute": "rate_limit_remaining",
                "Datatype": "int",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "So request con",
            },
            {
                "Attribute": "rate_limit_limit",
                "Datatype": "int",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Han muc",
            },
            {
                "Attribute": "rate_limit_reset_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Reset",
            },
            {
                "Attribute": "last_used_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Lan dung cuoi",
            },
            {
                "Attribute": "total_requests",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Tong request",
            },
            {
                "Attribute": "last_validated_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Lan kiem tra cuoi",
            },
            {
                "Attribute": "validation_error",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Loi xac thuc",
            },
        ],
    )

    add_entity(
        "ModelBuild",
        "Build thu thap dac trung phuc vu mo hinh",
        [
            {
                "Attribute": "repo_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_repositories._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Repo nguon",
            },
            {
                "Attribute": "workflow_run_id",
                "Datatype": "int",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "ID workflow CI",
            },
            {
                "Attribute": "head_sha",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "SHA commit",
            },
            {
                "Attribute": "build_number",
                "Datatype": "int",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "So build",
            },
            {
                "Attribute": "build_created_at",
                "Datatype": "datetime",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Thoi gian tao",
            },
            {
                "Attribute": "status",
                "Datatype": "enum BuildStatus",
                "Constraint": "success|failure|cancelled|skipped|timed_out|neutral|unknown",
                "Nullable": "No",
                "Default": "success",
                "Description": "Ket qua CI",
            },
            {
                "Attribute": "extraction_status",
                "Datatype": "enum ExtractionStatus",
                "Constraint": "pending|completed|partial|failed",
                "Nullable": "No",
                "Default": "pending",
                "Description": "Trang thai extract",
            },
            {
                "Attribute": "error_message",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Loi extract",
            },
            {
                "Attribute": "is_missing_commit",
                "Datatype": "bool",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "False",
                "Description": "Thieu commit",
            },
            {
                "Attribute": "features",
                "Datatype": "Dict",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "{}",
                "Description": "Feature ket qua",
            },
        ],
    )

    add_entity(
        "ModelRepository",
        "Repo duoc import de train mo hinh",
        [
            {
                "Attribute": "user_id",
                "Datatype": "ObjectId",
                "Constraint": "FK users._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Chu so huu",
            },
            {
                "Attribute": "provider",
                "Datatype": "enum Provider",
                "Constraint": "github",
                "Nullable": "No",
                "Default": "github",
                "Description": "Nha cung cap",
            },
            {
                "Attribute": "full_name",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "owner/repo",
            },
            {
                "Attribute": "github_repo_id",
                "Datatype": "int",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Repo id",
            },
            {
                "Attribute": "default_branch",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Nganh mac dinh",
            },
            {
                "Attribute": "is_private",
                "Datatype": "bool",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "False",
                "Description": "Repo private",
            },
            {
                "Attribute": "main_lang",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Ngon ngu chinh",
            },
            {
                "Attribute": "test_frameworks",
                "Datatype": "List[TestFramework]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Framework test",
            },
            {
                "Attribute": "source_languages",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Ngon ngu nguon",
            },
            {
                "Attribute": "ci_provider",
                "Datatype": "enum CIProvider",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "github_actions",
                "Description": "CI su dung",
            },
            {
                "Attribute": "installation_id",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "GitHub App installation",
            },
            {
                "Attribute": "import_status",
                "Datatype": "enum ImportStatus",
                "Constraint": "queued|importing|imported|failed",
                "Nullable": "No",
                "Default": "queued",
                "Description": "Trang thai import",
            },
            {
                "Attribute": "total_builds_imported",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "So build da import",
            },
            {
                "Attribute": "last_scanned_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Scan Sonar gan nhat",
            },
            {
                "Attribute": "last_sync_error",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Loi sync",
            },
            {
                "Attribute": "notes",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Ghi chu",
            },
            {
                "Attribute": "last_synced_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Lan sync cuoi",
            },
            {
                "Attribute": "last_sync_status",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "KQ sync cuoi",
            },
            {
                "Attribute": "latest_synced_run_created_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Run moi nhat da sync",
            },
            {
                "Attribute": "max_builds_to_ingest",
                "Datatype": "int",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Gioi han ingest",
            },
            {
                "Attribute": "metadata",
                "Datatype": "Dict[str,Any]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "{}",
                "Description": "Metadata phu",
            },
        ],
    )

    add_entity(
        "OAuthIdentity",
        "Lien ket OAuth ben ngoai",
        [
            {
                "Attribute": "user_id",
                "Datatype": "ObjectId",
                "Constraint": "FK users._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Nguoi dung",
            },
            {
                "Attribute": "provider",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Ten nha cung cap",
            },
            {
                "Attribute": "external_user_id",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "ID ngoai",
            },
            {
                "Attribute": "access_token",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Access token",
            },
            {
                "Attribute": "refresh_token",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Refresh token",
            },
            {
                "Attribute": "token_expires_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Het han",
            },
            {
                "Attribute": "scopes",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Scopes",
            },
            {
                "Attribute": "account_login",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Login",
            },
            {
                "Attribute": "account_name",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Ten",
            },
            {
                "Attribute": "account_avatar_url",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Avatar",
            },
            {
                "Attribute": "connected_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Thoi diem ket noi",
            },
        ],
    )

    add_entity(
        "PipelineRun",
        "Theo doi thuc thi pipeline extract feature",
        [
            {
                "Attribute": "build_sample_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_builds._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Build nguon",
            },
            {
                "Attribute": "repo_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_repositories._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Repo",
            },
            {
                "Attribute": "workflow_run_id",
                "Datatype": "int",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Workflow run",
            },
            {
                "Attribute": "status",
                "Datatype": "str",
                "Constraint": "pending|running|completed|failed|cancelled",
                "Nullable": "No",
                "Default": "pending",
                "Description": "Trang thai",
            },
            {
                "Attribute": "started_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Bat dau",
            },
            {
                "Attribute": "completed_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Hoan tat",
            },
            {
                "Attribute": "duration_ms",
                "Datatype": "float",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Thoi luong",
            },
            {
                "Attribute": "node_results",
                "Datatype": "List[NodeExecutionResult]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Ket qua tung node",
            },
            {
                "Attribute": "feature_count",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "So feature",
            },
            {
                "Attribute": "features_extracted",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Danh sach feature",
            },
            {
                "Attribute": "errors",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Loi",
            },
            {
                "Attribute": "warnings",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Canh bao",
            },
            {
                "Attribute": "dag_version",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Hash DAG",
            },
            {
                "Attribute": "nodes_requested",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "So node yeu cau",
            },
            {
                "Attribute": "nodes_executed",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "So node chay",
            },
            {
                "Attribute": "nodes_succeeded",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Node thanh cong",
            },
            {
                "Attribute": "nodes_failed",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Node that bai",
            },
            {
                "Attribute": "nodes_skipped",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Node bo qua",
            },
            {
                "Attribute": "total_retries",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Tong retry",
            },
        ],
    )

    add_entity(
        "ScanJob",
        "Job chay Sonar scan",
        [
            {
                "Attribute": "repo_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_repositories._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Repo",
            },
            {
                "Attribute": "build_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_builds._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Build",
            },
            {
                "Attribute": "commit_sha",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Commit",
            },
            {
                "Attribute": "status",
                "Datatype": "enum ScanJobStatus",
                "Constraint": "pending|running|success|failed",
                "Nullable": "No",
                "Default": "pending",
                "Description": "Trang thai",
            },
            {
                "Attribute": "worker_id",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Worker thuc thi",
            },
            {
                "Attribute": "started_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Bat dau",
            },
            {
                "Attribute": "finished_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Ket thuc",
            },
            {
                "Attribute": "sonar_component_key",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Sonar component",
            },
            {
                "Attribute": "error_message",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Loi",
            },
            {
                "Attribute": "logs",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Log",
            },
        ],
    )

    add_entity(
        "ScanResult",
        "Luu ket qua SonarQube",
        [
            {
                "Attribute": "repo_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_repositories._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Repo",
            },
            {
                "Attribute": "job_id",
                "Datatype": "ObjectId",
                "Constraint": "FK scan_jobs._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Scan job",
            },
            {
                "Attribute": "sonar_project_key",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Project key",
            },
            {
                "Attribute": "metrics",
                "Datatype": "Dict[str,number|string]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "{}",
                "Description": "Ket qua do",
            },
        ],
    )

    add_entity(
        "SonarScanPending",
        "Tracking scan Sonar async",
        [
            {
                "Attribute": "build_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_builds/enrichment_builds._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Build lien quan",
            },
            {
                "Attribute": "build_type",
                "Datatype": "str",
                "Constraint": "literal model|enrichment",
                "Nullable": "No",
                "Default": "model",
                "Description": "Loai build",
            },
            {
                "Attribute": "component_key",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Sonar component",
            },
            {
                "Attribute": "commit_sha",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Commit",
            },
            {
                "Attribute": "repo_url",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "URL repo",
            },
            {
                "Attribute": "status",
                "Datatype": "enum ScanPendingStatus",
                "Constraint": "scanning|completed|failed",
                "Nullable": "No",
                "Default": "scanning",
                "Description": "Trang thai",
            },
            {
                "Attribute": "error_message",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Loi",
            },
            {
                "Attribute": "metrics",
                "Datatype": "Dict",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Ket qua",
            },
            {
                "Attribute": "started_at",
                "Datatype": "datetime",
                "Constraint": "auto-set",
                "Nullable": "No",
                "Default": "now() UTC",
                "Description": "Bat dau",
            },
            {
                "Attribute": "completed_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Hoan tat",
            },
        ],
    )

    add_entity(
        "User",
        "Tai khoan nguoi dung",
        [
            {
                "Attribute": "email",
                "Datatype": "str",
                "Constraint": "required, unique? (business)",
                "Nullable": "No",
                "Default": "-",
                "Description": "Email dang nhap",
            },
            {
                "Attribute": "name",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Ten hien thi",
            },
            {
                "Attribute": "role",
                "Datatype": "literal admin|user",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "user",
                "Description": "Quyen",
            },
        ],
    )

    add_entity(
        "WorkflowRunRaw",
        "Luu raw workflow run tu CI",
        [
            {
                "Attribute": "repo_id",
                "Datatype": "ObjectId",
                "Constraint": "FK model_repositories._id",
                "Nullable": "No",
                "Default": "-",
                "Description": "Repo",
            },
            {
                "Attribute": "workflow_run_id",
                "Datatype": "int",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "ID CI",
            },
            {
                "Attribute": "ci_provider",
                "Datatype": "enum CIProvider",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "github_actions",
                "Description": "Nha cung cap CI",
            },
            {
                "Attribute": "head_sha",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Commit",
            },
            {
                "Attribute": "run_number",
                "Datatype": "int",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "So run",
            },
            {
                "Attribute": "status",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Trang thai",
            },
            {
                "Attribute": "conclusion",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Ket luan",
            },
            {
                "Attribute": "branch",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Nganh",
            },
            {
                "Attribute": "ci_created_at",
                "Datatype": "datetime",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Thoi gian tao tren CI",
            },
            {
                "Attribute": "ci_updated_at",
                "Datatype": "datetime",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Cap nhat tren CI",
            },
            {
                "Attribute": "raw_payload",
                "Datatype": "Dict[str,Any]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "{}",
                "Description": "Payload goc",
            },
        ],
    )

    add_entity(
        "NodeExecutionResult (embedded)",
        "Ket qua tung node trong PipelineRun",
        [
            {
                "Attribute": "node_name",
                "Datatype": "str",
                "Constraint": "required",
                "Nullable": "No",
                "Default": "-",
                "Description": "Ten node",
            },
            {
                "Attribute": "status",
                "Datatype": "str",
                "Constraint": "success|failed|skipped",
                "Nullable": "No",
                "Default": "-",
                "Description": "Trang thai",
            },
            {
                "Attribute": "started_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Bat dau",
            },
            {
                "Attribute": "completed_at",
                "Datatype": "datetime",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Hoan tat",
            },
            {
                "Attribute": "duration_ms",
                "Datatype": "float",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "Thoi luong",
            },
            {
                "Attribute": "features_extracted",
                "Datatype": "List[str]",
                "Constraint": "-",
                "Nullable": "No",
                "Default": "[]",
                "Description": "Feature tao ra",
            },
            {
                "Attribute": "error",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Loi",
            },
            {
                "Attribute": "warning",
                "Datatype": "str",
                "Constraint": "-",
                "Nullable": "Yes",
                "Default": "None",
                "Description": "Canh bao",
            },
            {
                "Attribute": "retry_count",
                "Datatype": "int",
                "Constraint": ">=0",
                "Nullable": "No",
                "Default": "0",
                "Description": "So lan retry",
            },
        ],
    )

    return doc


def main():
    doc = build_document()
    output_path = Path("backend/app/entities/entity_design.docx")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(output_path)
    print(f"Generated: {output_path}")


if __name__ == "__main__":
    main()
