from app.pipeline.core.registry import (
    FeatureMetadata,
    FeatureCategory,
    FeatureDataType,
    FeatureSource,
)

SNAPSHOT = {
    "gh_repo_age": FeatureMetadata(
        display_name="Repository Age",
        description="Number of days since the first commit in the repository",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        source=FeatureSource.GIT_REPO,
        example_value="365.5",
        unit="days",
    ),
    "gh_repo_num_commits": FeatureMetadata(
        display_name="Total Commits",
        description="Total number of commits in the repository history",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.GIT_REPO,
        example_value="1234",
    ),
    "gh_sloc": FeatureMetadata(
        display_name="Source Lines of Code",
        description="Total lines of source code (excluding tests, vendor, etc.)",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.GIT_REPO,
        example_value="50000",
        unit="lines",
    ),
    "gh_test_lines_per_kloc": FeatureMetadata(
        display_name="Test Lines per KLOC",
        description="Number of test code lines per 1000 lines of source code",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        source=FeatureSource.COMPUTED,
        example_value="150.5",
    ),
    "gh_test_cases_per_kloc": FeatureMetadata(
        display_name="Test Cases per KLOC",
        description="Number of test case definitions per 1000 lines of source code",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        source=FeatureSource.COMPUTED,
        example_value="12.3",
    ),
    "gh_asserts_case_per_kloc": FeatureMetadata(
        display_name="Assertions per KLOC",
        description="Number of assertion statements per 1000 lines of source code",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        source=FeatureSource.COMPUTED,
        example_value="25.7",
    ),
    "gh_project_name": FeatureMetadata(
        display_name="Project Name",
        description="Full repository name (owner/repo)",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.METADATA,
        nullable=False,
        example_value="owner/repo-name",
    ),
    "gh_is_pr": FeatureMetadata(
        display_name="Is Pull Request",
        description="Whether this build was triggered by a pull request",
        category=FeatureCategory.PR_INFO,
        data_type=FeatureDataType.BOOLEAN,
        source=FeatureSource.WORKFLOW_RUN,
        nullable=False,
        example_value="true",
    ),
    "gh_pr_created_at": FeatureMetadata(
        display_name="PR Created At",
        description="Timestamp when the pull request was created",
        category=FeatureCategory.PR_INFO,
        data_type=FeatureDataType.DATETIME,
        source=FeatureSource.GITHUB_API,
        example_value="2024-01-15T10:30:00Z",
    ),
    "gh_pull_req_num": FeatureMetadata(
        display_name="PR Number",
        description="Pull request number if applicable",
        category=FeatureCategory.PR_INFO,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.WORKFLOW_RUN,
        example_value="42",
    ),
    "gh_lang": FeatureMetadata(
        display_name="Main Language",
        description="Primary programming language of the repository",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.METADATA,
        example_value="python",
    ),
    "git_branch": FeatureMetadata(
        display_name="Branch Name",
        description="Git branch that triggered this build",
        category=FeatureCategory.WORKFLOW,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.WORKFLOW_RUN,
        example_value="main",
    ),
    "git_trigger_commit": FeatureMetadata(
        display_name="Trigger Commit",
        description="Git commit SHA that triggered this workflow run",
        category=FeatureCategory.WORKFLOW,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.WORKFLOW_RUN,
        example_value="abc123def456",
    ),
    "ci_provider": FeatureMetadata(
        display_name="CI Provider",
        description="The CI/CD platform used (github_actions, gitlab_ci, etc.)",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.METADATA,
        nullable=False,
        example_value="github_actions",
    ),
    "gh_build_started_at": FeatureMetadata(
        display_name="Build Started At",
        description="Timestamp when the build workflow started",
        category=FeatureCategory.WORKFLOW,
        data_type=FeatureDataType.DATETIME,
        source=FeatureSource.WORKFLOW_RUN,
        example_value="2024-01-15T10:35:00Z",
    ),
}

REPO_METADATA = {
    **SNAPSHOT,
}
