from app.pipeline.core.registry import (
    FeatureMetadata,
    FeatureCategory,
    FeatureDataType,
    FeatureSource,
)


# Reliability Metrics (Bugs)
RELIABILITY = {
    "sonar_bugs": FeatureMetadata(
        display_name="Bugs",
        description="Number of bug issues detected by SonarQube",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        nullable=False,
        example_value="5",
    ),
    "sonar_reliability_issues": FeatureMetadata(
        display_name="Reliability Issues",
        description="Total number of reliability issues",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="8",
    ),
    "sonar_reliability_rating": FeatureMetadata(
        display_name="Reliability Rating",
        description="Reliability rating (A-E) based on bug severity",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.COMPUTED,
        example_value="A",
    ),
    "sonar_reliability_remediation_effort": FeatureMetadata(
        display_name="Reliability Remediation Effort",
        description="Estimated time to fix all reliability issues",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="120",
        unit="minutes",
    ),
    "sonar_software_quality_reliability_rating": FeatureMetadata(
        display_name="SW Quality Reliability Rating",
        description="Software quality reliability rating",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.COMPUTED,
        example_value="B",
    ),
    "sonar_software_quality_reliability_issues": FeatureMetadata(
        display_name="SW Quality Reliability Issues",
        description="Software quality reliability issues count",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="3",
    ),
    "sonar_software_quality_reliability_remediation_effort": FeatureMetadata(
        display_name="SW Quality Reliability Remediation",
        description="Software quality reliability remediation effort",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="60",
        unit="minutes",
    ),
}


# Security Metrics (Vulnerabilities)
SECURITY = {
    "sonar_vulnerabilities": FeatureMetadata(
        display_name="Vulnerabilities",
        description="Number of security vulnerabilities detected",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        nullable=False,
        example_value="2",
    ),
    "sonar_security_issues": FeatureMetadata(
        display_name="Security Issues",
        description="Total number of security issues",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="4",
    ),
    "sonar_security_rating": FeatureMetadata(
        display_name="Security Rating",
        description="Security rating (A-E) based on vulnerability severity",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.COMPUTED,
        example_value="A",
    ),
    "sonar_security_hotspots": FeatureMetadata(
        display_name="Security Hotspots",
        description="Number of security hotspots that need review",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="3",
    ),
    "sonar_security_remediation_effort": FeatureMetadata(
        display_name="Security Remediation Effort",
        description="Estimated time to fix all security issues",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="180",
        unit="minutes",
    ),
    "sonar_security_review_rating": FeatureMetadata(
        display_name="Security Review Rating",
        description="Rating based on reviewed security hotspots",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.COMPUTED,
        example_value="B",
    ),
    "sonar_security_hotspots_to_review_status": FeatureMetadata(
        display_name="Hotspots Review Status",
        description="Percentage of security hotspots that have been reviewed",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.FLOAT,
        source=FeatureSource.COMPUTED,
        example_value="75.0",
        unit="percent",
    ),
    "sonar_software_quality_security_rating": FeatureMetadata(
        display_name="SW Quality Security Rating",
        description="Software quality security rating",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.COMPUTED,
        example_value="A",
    ),
    "sonar_software_quality_security_issues": FeatureMetadata(
        display_name="SW Quality Security Issues",
        description="Software quality security issues count",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="1",
    ),
    "sonar_software_quality_security_remediation_effort": FeatureMetadata(
        display_name="SW Quality Security Remediation",
        description="Software quality security remediation effort",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="30",
        unit="minutes",
    ),
}


# Maintainability Metrics (Code Smells, Technical Debt)
MAINTAINABILITY = {
    "sonar_code_smells": FeatureMetadata(
        display_name="Code Smells",
        description="Number of code smell issues detected",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        nullable=False,
        example_value="42",
    ),
    "sonar_sqale_index": FeatureMetadata(
        display_name="Technical Debt",
        description="Total technical debt in minutes (SQALE index)",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="1200",
        unit="minutes",
    ),
    "sonar_sqale_debt_ratio": FeatureMetadata(
        display_name="Technical Debt Ratio",
        description="Ratio of technical debt to development cost",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.FLOAT,
        source=FeatureSource.COMPUTED,
        example_value="2.5",
        unit="percent",
    ),
    "sonar_sqale_rating": FeatureMetadata(
        display_name="Maintainability Rating",
        description="Maintainability rating (A-E) based on technical debt ratio",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.COMPUTED,
        example_value="A",
    ),
    "sonar_maintainability_issues": FeatureMetadata(
        display_name="Maintainability Issues",
        description="Total number of maintainability issues",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="25",
    ),
    "sonar_development_cost": FeatureMetadata(
        display_name="Development Cost",
        description="Estimated development cost of the project",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.COMPUTED,
        example_value="50000",
    ),
    "sonar_effort_to_reach_maintainability_rating_a": FeatureMetadata(
        display_name="Effort to Reach A Rating",
        description="Effort needed to reach maintainability rating A",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="480",
        unit="minutes",
    ),
    "sonar_software_quality_maintainability_debt_ratio": FeatureMetadata(
        display_name="SW Quality Debt Ratio",
        description="Software quality maintainability debt ratio",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.FLOAT,
        source=FeatureSource.COMPUTED,
        example_value="1.8",
        unit="percent",
    ),
    "sonar_software_quality_maintainability_remediation_effort": FeatureMetadata(
        display_name="SW Quality Maintainability Remediation",
        description="Software quality maintainability remediation effort",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="960",
        unit="minutes",
    ),
    "sonar_software_quality_maintainability_rating": FeatureMetadata(
        display_name="SW Quality Maintainability Rating",
        description="Software quality maintainability rating",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.COMPUTED,
        example_value="B",
    ),
    "sonar_effort_to_reach_software_quality_maintainability_rating_a": FeatureMetadata(
        display_name="Effort to Reach SW Quality A Rating",
        description="Effort to reach software quality maintainability rating A",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="720",
        unit="minutes",
    ),
    "sonar_software_quality_maintainability_issues": FeatureMetadata(
        display_name="SW Quality Maintainability Issues",
        description="Software quality maintainability issues count",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="18",
    ),
}


# Coverage Metrics
COVERAGE = {
    "sonar_coverage": FeatureMetadata(
        display_name="Code Coverage",
        description="Overall code coverage percentage",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.FLOAT,
        source=FeatureSource.COMPUTED,
        example_value="78.5",
        unit="percent",
    ),
    "sonar_line_coverage": FeatureMetadata(
        display_name="Line Coverage",
        description="Percentage of lines covered by tests",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.FLOAT,
        source=FeatureSource.COMPUTED,
        example_value="82.3",
        unit="percent",
    ),
    "sonar_lines_to_cover": FeatureMetadata(
        display_name="Lines to Cover",
        description="Number of lines that should be covered by tests",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="5000",
    ),
    "sonar_uncovered_lines": FeatureMetadata(
        display_name="Uncovered Lines",
        description="Number of lines not covered by tests",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="885",
    ),
}


# Duplication Metrics
DUPLICATION = {
    "sonar_duplicated_lines_density": FeatureMetadata(
        display_name="Duplicated Lines %",
        description="Percentage of duplicated lines in the codebase",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.FLOAT,
        source=FeatureSource.COMPUTED,
        example_value="3.2",
        unit="percent",
    ),
    "sonar_duplicated_lines": FeatureMetadata(
        display_name="Duplicated Lines",
        description="Total number of duplicated lines",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="450",
    ),
    "sonar_duplicated_blocks": FeatureMetadata(
        display_name="Duplicated Blocks",
        description="Number of duplicated code blocks",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="12",
    ),
    "sonar_duplicated_files": FeatureMetadata(
        display_name="Duplicated Files",
        description="Number of files containing duplicated code",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="8",
    ),
}


# Complexity Metrics
COMPLEXITY = {
    "sonar_cognitive_complexity": FeatureMetadata(
        display_name="Cognitive Complexity",
        description="Total cognitive complexity of the codebase",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="1250",
    ),
    "sonar_complexity": FeatureMetadata(
        display_name="Cyclomatic Complexity",
        description="Total cyclomatic complexity of the codebase",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="890",
    ),
}


# Size Metrics
SIZE = {
    "sonar_ncloc": FeatureMetadata(
        display_name="Lines of Code (No Comments)",
        description="Number of physical lines containing code (excluding comments)",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="25000",
    ),
    "sonar_lines": FeatureMetadata(
        display_name="Total Lines",
        description="Total number of lines in the project",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="35000",
    ),
    "sonar_files": FeatureMetadata(
        display_name="Files Count",
        description="Total number of files analyzed",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="150",
    ),
    "sonar_classes": FeatureMetadata(
        display_name="Classes Count",
        description="Total number of classes",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="85",
    ),
    "sonar_functions": FeatureMetadata(
        display_name="Functions Count",
        description="Total number of functions",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="420",
    ),
    "sonar_statements": FeatureMetadata(
        display_name="Statements Count",
        description="Total number of statements",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="12500",
    ),
    "sonar_ncloc_language_distribution": FeatureMetadata(
        display_name="Language Distribution",
        description="Distribution of lines of code by language",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.COMPUTED,
        example_value="py=15000;js=10000",
    ),
    "sonar_comment_lines_density": FeatureMetadata(
        display_name="Comment Density",
        description="Percentage of comment lines",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.FLOAT,
        source=FeatureSource.COMPUTED,
        example_value="18.5",
        unit="percent",
    ),
    "sonar_comment_lines": FeatureMetadata(
        display_name="Comment Lines",
        description="Total number of comment lines",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="5500",
    ),
}


# Quality Gate Metrics
QUALITY_GATE = {
    "sonar_alert_status": FeatureMetadata(
        display_name="Quality Gate Status",
        description="Overall quality gate status (OK, WARN, ERROR)",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.COMPUTED,
        nullable=False,
        example_value="OK",
    ),
    "sonar_quality_gate_details": FeatureMetadata(
        display_name="Quality Gate Details",
        description="Detailed quality gate conditions and their status",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        source=FeatureSource.COMPUTED,
        example_value='{"level":"OK","conditions":[...]}',
    ),
}


# Issue Severity Metrics
ISSUES = {
    "sonar_software_quality_blocker_issues": FeatureMetadata(
        display_name="Blocker Issues",
        description="Number of blocker severity issues",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="0",
    ),
    "sonar_critical_violations": FeatureMetadata(
        display_name="Critical Violations",
        description="Number of critical severity violations",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="2",
    ),
    "sonar_violations": FeatureMetadata(
        display_name="Total Violations",
        description="Total number of all violations",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="47",
    ),
    "sonar_software_quality_high_issues": FeatureMetadata(
        display_name="High Severity Issues",
        description="Number of high severity issues",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="5",
    ),
    "sonar_info_violations": FeatureMetadata(
        display_name="Info Violations",
        description="Number of info severity violations",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="10",
    ),
    "sonar_software_quality_low_issues": FeatureMetadata(
        display_name="Low Severity Issues",
        description="Number of low severity issues",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="15",
    ),
    "sonar_software_quality_info_issues": FeatureMetadata(
        display_name="Info Level Issues",
        description="Number of info level quality issues",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="8",
    ),
    "sonar_minor_violations": FeatureMetadata(
        display_name="Minor Violations",
        description="Number of minor severity violations",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="20",
    ),
    "sonar_major_violations": FeatureMetadata(
        display_name="Major Violations",
        description="Number of major severity violations",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="12",
    ),
    "sonar_software_quality_medium_issues": FeatureMetadata(
        display_name="Medium Severity Issues",
        description="Number of medium severity issues",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="10",
    ),
    "sonar_open_issues": FeatureMetadata(
        display_name="Open Issues",
        description="Number of currently open issues",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        source=FeatureSource.COMPUTED,
        example_value="35",
    ),
    "sonar_last_commit_date": FeatureMetadata(
        display_name="Last Commit Date",
        description="Date of the last commit analyzed by SonarQube",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.DATETIME,
        source=FeatureSource.COMPUTED,
        example_value="2024-01-15T10:30:00Z",
    ),
}


# Mapping from YAML keys to feature names (for backward compatibility)
SONAR_KEY_TO_FEATURE = {
    "bugs": "sonar_bugs",
    "reliability_issues": "sonar_reliability_issues",
    "reliability_rating": "sonar_reliability_rating",
    "software_quality_reliability_remediation_effort": "sonar_software_quality_reliability_remediation_effort",
    "software_quality_reliability_issues": "sonar_software_quality_reliability_issues",
    "reliability_remediation_effort": "sonar_reliability_remediation_effort",
    "software_quality_reliability_rating": "sonar_software_quality_reliability_rating",
    "vulnerabilities": "sonar_vulnerabilities",
    "security_issues": "sonar_security_issues",
    "security_rating": "sonar_security_rating",
    "security_hotspots": "sonar_security_hotspots",
    "software_quality_security_rating": "sonar_software_quality_security_rating",
    "software_quality_security_issues": "sonar_software_quality_security_issues",
    "software_quality_security_remediation_effort": "sonar_software_quality_security_remediation_effort",
    "security_remediation_effort": "sonar_security_remediation_effort",
    "security_review_rating": "sonar_security_review_rating",
    "security_hotspots_to_review_status": "sonar_security_hotspots_to_review_status",
    "code_smells": "sonar_code_smells",
    "sqale_index": "sonar_sqale_index",
    "sqale_debt_ratio": "sonar_sqale_debt_ratio",
    "sqale_rating": "sonar_sqale_rating",
    "maintainability_issues": "sonar_maintainability_issues",
    "development_cost": "sonar_development_cost",
    "effort_to_reach_maintainability_rating_a": "sonar_effort_to_reach_maintainability_rating_a",
    "software_quality_maintainability_debt_ratio": "sonar_software_quality_maintainability_debt_ratio",
    "software_quality_maintainability_remediation_effort": "sonar_software_quality_maintainability_remediation_effort",
    "software_quality_maintainability_rating": "sonar_software_quality_maintainability_rating",
    "effort_to_reach_software_quality_maintainability_rating_a": "sonar_effort_to_reach_software_quality_maintainability_rating_a",
    "coverage": "sonar_coverage",
    "line_coverage": "sonar_line_coverage",
    "lines_to_cover": "sonar_lines_to_cover",
    "uncovered_lines": "sonar_uncovered_lines",
    "duplicated_lines_density": "sonar_duplicated_lines_density",
    "duplicated_lines": "sonar_duplicated_lines",
    "duplicated_blocks": "sonar_duplicated_blocks",
    "duplicated_files": "sonar_duplicated_files",
    "cognitive_complexity": "sonar_cognitive_complexity",
    "complexity": "sonar_complexity",
    "ncloc": "sonar_ncloc",
    "lines": "sonar_lines",
    "files": "sonar_files",
    "classes": "sonar_classes",
    "functions": "sonar_functions",
    "statements": "sonar_statements",
    "ncloc_language_distribution": "sonar_ncloc_language_distribution",
    "comment_lines_density": "sonar_comment_lines_density",
    "comment_lines": "sonar_comment_lines",
    "alert_status": "sonar_alert_status",
    "quality_gate_details": "sonar_quality_gate_details",
    "software_quality_blocker_issues": "sonar_software_quality_blocker_issues",
    "critical_violations": "sonar_critical_violations",
    "violations": "sonar_violations",
    "software_quality_high_issues": "sonar_software_quality_high_issues",
    "info_violations": "sonar_info_violations",
    "software_quality_low_issues": "sonar_software_quality_low_issues",
    "software_quality_maintainability_issues": "sonar_software_quality_maintainability_issues",
    "software_quality_info_issues": "sonar_software_quality_info_issues",
    "minor_violations": "sonar_minor_violations",
    "major_violations": "sonar_major_violations",
    "software_quality_medium_issues": "sonar_software_quality_medium_issues",
    "open_issues": "sonar_open_issues",
    "last_commit_date": "sonar_last_commit_date",
}

SONAR_METADATA = {
    **RELIABILITY,
    **SECURITY,
    **MAINTAINABILITY,
    **COVERAGE,
    **DUPLICATION,
    **COMPLEXITY,
    **SIZE,
    **QUALITY_GATE,
    **ISSUES,
}


def get_sonar_feature_names() -> list[str]:
    """Get list of all SonarQube feature names."""
    return list(SONAR_METADATA.keys())


def get_sonar_metric_keys() -> list[str]:
    """Get list of original SonarQube metric keys (for API calls)."""
    return list(SONAR_KEY_TO_FEATURE.keys())
