"""Feature definitions for Build domain."""

from typing import Dict

from app.tasks.pipeline.feature_dag._types import (
    FeatureCategory,
    FeatureDataType,
    FeatureDefinition,
    FeatureResource,
    OutputFormat,
)

BUILD_FEATURES: Dict[str, FeatureDefinition] = {
    "tr_build_id": FeatureDefinition(
        name="tr_build_id",
        display_name="Build ID",
        description="Unique identifier for the workflow run",
        category=FeatureCategory.WORKFLOW,
        data_type=FeatureDataType.INTEGER,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
    ),
    "tr_build_number": FeatureDefinition(
        name="tr_build_number",
        display_name="Build Number",
        description="Sequential build number for this workflow",
        category=FeatureCategory.WORKFLOW,
        data_type=FeatureDataType.INTEGER,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
    ),
    "tr_original_commit": FeatureDefinition(
        name="tr_original_commit",
        display_name="Original Commit",
        description="Original commit SHA that triggered the build",
        category=FeatureCategory.WORKFLOW,
        data_type=FeatureDataType.STRING,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
    ),
    "tr_status": FeatureDefinition(
        name="tr_status",
        display_name="Build Status",
        description="Normalized build status (passed, failed, cancelled, errored)",
        category=FeatureCategory.WORKFLOW,
        data_type=FeatureDataType.STRING,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
        valid_values=["passed", "failed", "cancelled", "errored", "unknown"],
    ),
    "tr_status_num": FeatureDefinition(
        name="tr_status_num",
        display_name="Build Status Numeric",
        description="Numeric build status for model input (0=passed, 1=failed, -1=other)",
        category=FeatureCategory.WORKFLOW,
        data_type=FeatureDataType.INTEGER,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
        valid_values=[-1, 0, 1],
    ),
    "tr_duration": FeatureDefinition(
        name="tr_duration",
        display_name="Build Duration",
        description="Build duration in seconds",
        category=FeatureCategory.WORKFLOW,
        data_type=FeatureDataType.INTEGER,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
        unit="seconds",
    ),
    "tr_log_lan_all": FeatureDefinition(
        name="tr_log_lan_all",
        display_name="Source Languages",
        description="All source languages for the repository",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.LIST_STRING,
        extractor_node="build",
        required_resources=[FeatureResource.REPO],
        output_format=OutputFormat.COMMA_SEPARATED,
    ),
    "gh_project_name": FeatureDefinition(
        name="gh_project_name",
        display_name="Project Name",
        description="Full repository name (owner/repo)",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        extractor_node="build",
        required_resources=[FeatureResource.REPO],
    ),
    "gh_lang": FeatureDefinition(
        name="gh_lang",
        display_name="Primary Language",
        description="Primary programming language of the repository",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        extractor_node="build",
        required_resources=[FeatureResource.REPO],
    ),
    "ci_provider": FeatureDefinition(
        name="ci_provider",
        display_name="CI Provider",
        description="CI/CD provider name (github_actions, travis, circleci)",
        category=FeatureCategory.WORKFLOW,
        data_type=FeatureDataType.STRING,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
    ),
    "gh_build_started_at": FeatureDefinition(
        name="gh_build_started_at",
        display_name="Build Started At",
        description="Build start timestamp in ISO format",
        category=FeatureCategory.WORKFLOW,
        data_type=FeatureDataType.DATETIME,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
    ),
    "gh_is_pr": FeatureDefinition(
        name="gh_is_pr",
        display_name="Is PR Build",
        description="Whether this build is triggered by a pull request",
        category=FeatureCategory.PR_INFO,
        data_type=FeatureDataType.BOOLEAN,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
    ),
    "gh_pull_req_num": FeatureDefinition(
        name="gh_pull_req_num",
        display_name="PR Number",
        description="Pull request number (works with all CI providers)",
        category=FeatureCategory.PR_INFO,
        data_type=FeatureDataType.INTEGER,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
        nullable=True,
    ),
    "gh_pr_created_at": FeatureDefinition(
        name="gh_pr_created_at",
        display_name="PR Created At",
        description="Pull request creation timestamp from GitHub API",
        category=FeatureCategory.PR_INFO,
        data_type=FeatureDataType.DATETIME,
        extractor_node="build",
        required_resources=[FeatureResource.GITHUB_API, FeatureResource.BUILD_RUN],
        nullable=True,
    ),
    "day_week": FeatureDefinition(
        name="day_week",
        display_name="Day of Week",
        description="Day of week when build was triggered (Monday-Sunday)",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.STRING,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
        valid_values=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    ),
    "time_of_day": FeatureDefinition(
        name="time_of_day",
        display_name="Hour of Day",
        description="Hour when build was triggered (0-23 UTC)",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.INTEGER,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
        valid_range=(0, 23),
    ),
    "build_time_sin": FeatureDefinition(
        name="build_time_sin",
        display_name="Build Time Sine",
        description="Sine encoding of build hour for cyclic representation",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.FLOAT,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
        valid_range=(-1.0, 1.0),
    ),
    "build_time_cos": FeatureDefinition(
        name="build_time_cos",
        display_name="Build Time Cosine",
        description="Cosine encoding of build hour for cyclic representation",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.FLOAT,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
        valid_range=(-1.0, 1.0),
    ),
    "build_hour_risk_score": FeatureDefinition(
        name="build_hour_risk_score",
        display_name="Build Hour Risk Score",
        description="Risk score based on build hour (higher at night)",
        category=FeatureCategory.METADATA,
        data_type=FeatureDataType.FLOAT,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
        valid_range=(0.0, 1.0),
    ),
    "gh_has_bug_label": FeatureDefinition(
        name="gh_has_bug_label",
        display_name="Has Bug Label",
        description="Whether the PR has any bug-related labels",
        category=FeatureCategory.PR_INFO,
        data_type=FeatureDataType.BOOLEAN,
        extractor_node="build",
        required_resources=[FeatureResource.BUILD_RUN],
    ),
}
