"""Feature definitions for Repository domain."""

from typing import Dict

from app.tasks.pipeline.feature_dag._types import (
    FeatureCategory,
    FeatureDataType,
    FeatureDefinition,
    FeatureResource,
)

REPOSITORY_FEATURES: Dict[str, FeatureDefinition] = {
    "gh_num_issue_comments": FeatureDefinition(
        name="gh_num_issue_comments",
        display_name="Issue Comments",
        description="Number of issue/discussion comments on the PR",
        category=FeatureCategory.DISCUSSION,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GITHUB_API, FeatureResource.BUILD_RUN],
    ),
    "gh_num_commit_comments": FeatureDefinition(
        name="gh_num_commit_comments",
        display_name="Commit Comments",
        description="Number of comments on commits in this build",
        category=FeatureCategory.DISCUSSION,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GITHUB_API],
    ),
    "gh_num_pr_comments": FeatureDefinition(
        name="gh_num_pr_comments",
        display_name="PR Review Comments",
        description="Number of code review comments on the PR",
        category=FeatureCategory.DISCUSSION,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GITHUB_API, FeatureResource.BUILD_RUN],
    ),
    "gh_description_complexity": FeatureDefinition(
        name="gh_description_complexity",
        display_name="Description Complexity",
        description="Word count of PR title + body",
        category=FeatureCategory.DISCUSSION,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GITHUB_API],
        nullable=True,
    ),
    "gh_repo_age": FeatureDefinition(
        name="gh_repo_age",
        display_name="Repository Age",
        description="Repository age in days (from first commit to build commit)",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_HISTORY],
        unit="days",
    ),
    "gh_repo_num_commits": FeatureDefinition(
        name="gh_repo_num_commits",
        display_name="Total Commits",
        description="Total number of commits in repository history",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "gh_sloc": FeatureDefinition(
        name="gh_sloc",
        display_name="Source Lines of Code",
        description="Total source lines of code (excluding comments)",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_WORKTREE],
        nullable=True,
    ),
    "gh_test_lines_per_kloc": FeatureDefinition(
        name="gh_test_lines_per_kloc",
        display_name="Test Lines / KLOC",
        description="Test lines per 1000 lines of source code",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_WORKTREE],
        nullable=True,
    ),
    "gh_test_cases_per_kloc": FeatureDefinition(
        name="gh_test_cases_per_kloc",
        display_name="Test Cases / KLOC",
        description="Test cases per 1000 lines of source code",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_WORKTREE],
        nullable=True,
    ),
    "gh_asserts_cases_per_kloc": FeatureDefinition(
        name="gh_asserts_cases_per_kloc",
        display_name="Assertions / KLOC",
        description="Assertions per 1000 lines of source code",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_WORKTREE],
        nullable=True,
    ),
}
